stages:
  prepare_data:
    cmd: python code/datasets/prepare_data.py --input data/raw/penguins.csv --train-output data/processed/train.csv --test-output data/processed/test.csv --test-size ${prepare.test_size} --random-state ${prepare.random_state} --iqr-factor ${prepare.iqr_factor}
    deps:
      - code/datasets/prepare_data.py
      - data/raw/penguins.csv
    params:
      - prepare.test_size
      - prepare.random_state
      - prepare.iqr_factor
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
